### ISSUE TITLE
intensity calibration

### ISSUE THREAD

**Issue by yuhui-xie** [minwoo0611/IA_LIO_SAM#1]
Hi, it's good to see your open code, may I ask how do you deal with the intensity calibration? namely, the physical model is prop to cosi / r. It seems that there is no relevant code in this project.

**Comment by minwoo0611** [comment]
Sorry to late comment.

We assume that it is important to match pointcloud between consecutive keyframes, so point's intensity is not different for short time. Also, we wanted to consider the large difference in intensity in the local area. Therefore, intensity calibration was not performed separately.

However, if it is considered for more accuracy, I also agree with your opinion that intensity calibration should be needed.

Thanks for your attention!
