### ISSUE TITLE
Beautiful work! Would like to ask how to adapt velodyne LiDAR? Thanks!

### ISSUE THREAD

**Issue by Robot-Yue** [minwoo0611/IA_LIO_SAM#4]

**Comment by minwoo0611** [comment]
Thank you for your interest, and sorry for the late reply!

Unfortunately, this repository is utilized the intensity and ambient channels. In the case ambient (these days, called NIR), it is only involved in Ouster LiDAR, this repository does not seem to fit your request.

However, even if it is no matters in utilizing only intensity information with velodyne LiDAR , I recommend to use the [intensity-slam](https://github.com/wh200720041/intensity_slam).
